services:
  postgres:
    image: postgres:16
    container_name: dcl-postgres
    environment:
      POSTGRES_DB: dcl
      POSTGRES_USER: dcl
      POSTGRES_PASSWORD: dcl
    ports:
      - "5432:5432"
    volumes:
      - dcl_pg_data:/var/lib/postgresql/data

volumes:
  dcl_pg_data:
